Update logo to a cleaner one
HorlogeSkynet/archey4 pull request #99
Opened 2021-04-27 19:17 UTC by GentleHoneyLover

I think this logo (from original archey) is much cleaner and slicker ;)

2021-04-27 19:18 UTC, GentleHoneyLover commented
This is how it'll look like:

<img width="534" alt="Screen Shot 2021-04-27 at 21 18 11" src="https://user-images.githubusercontent.com/38346023/116299528-1a216680-a79e-11eb-8823-5cc8b3ef70e1.png">

2021-04-28 12:38 UTC, HorlogeSkynet commented
Thanks for the PR ! I don't mind you editing the new "retro" one (not yet published), but I would rather you don't change the "default" one, without proper reviews from other users. From relatives, it corresponds well the way it is. Bye 👋

2021-04-28 12:41 UTC, GentleHoneyLover commented
@HorlogeSkynet, you're the boss :)) Updating just the retro one is fine for me...

Should I open a new PR for that?

2021-04-28 15:22 UTC, HorlogeSkynet commented
Great 👌 you may only add a commit to your own branch, it would update this PR automatically !

2021-04-28 17:44 UTC, HorlogeSkynet requested changes

2021-04-28 17:44 UTC, HorlogeSkynet commented on archey/logos/darwin.py
> +    """{c[0]}      {c[1]}#######    #######{c[0]}          """,
For "inverted-selection" consistency :

```suggestion
    """{c[0]}      {c[1]}#######{c[0]}    {c[1]}#######{c[0]}          """,
```

2021-04-28 17:44 UTC, HorlogeSkynet commented on archey/logos/darwin.py
> +    """{c[0]}        {c[6]}####     #####{c[0]}            """,
Same :

```suggestion
    """{c[0]}        {c[6]}####{c[0]}     {c[6]}#####{c[0]}            """,
```

2021-05-05 18:18 UTC, HorlogeSkynet approved these changes

2021-05-05 18:36 UTC, merged

2022-11-15 17:10 UTC, parkerbxyz commented
👋 Can this option (`--logo-style`) be set in a configuration file so it doesn't have to be included as an argument each time?

2022-11-15 18:51 UTC, HorlogeSkynet commented
Hi @parkerbxyz, yes it could. I'll add this to the TODO-list.

2022-11-15 19:00 UTC, ingrinder commented
See #124 - I would attach it to the card in projects but I'm not entirely sure how...!